name: Build Simpsons:Hit & Run UWP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Visual Studio with UWP toolset
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 2022
          msbuild-architecture: x64

      - name: Install dependencies
        run: |
          choco install ninja --yes  # Install Ninja if not already installed

      - name: Configure build environment
        run: |
          echo "Setting up environment for UWP build"
          echo "CXX=cl" >> $GITHUB_ENV  # Use Visual Studio's C++ compiler
          echo "CC=cl" >> $GITHUB_ENV   # Same for C
          echo "CFLAGS=-DWINAPI_FAMILY=WINAPI_FAMILY_APP" >> $GITHUB_ENV
          echo "CXXFLAGS=$CFLAGS" >> $GITHUB_ENV

      - name: Build Simpsons:Hit & Run UWP
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=uwp-toolchain.cmake -DCMAKE_BUILD_TYPE=Release ..
          ninja
