name: Build Mesa for UWP

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python and install dependencies
      - name: Set up Python and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja

      # Step 3: Clone the Mesa UWP fork
      - name: Clone Mesa UWP Fork
        run: |
          git clone https://github.com/worleydl/mesa-uwp.git
          cd mesa-uwp

      # Step 4: Set up Meson build for UWP
      - name: Set up Meson Build
        run: |
          meson setup build_release --wipe --backend=vs --uwp --buildtype=release -Dcpp_std=vc++17 -Dcpp_args=["'/D _XBOX_UWP'"] -Dc_args=["'/D _XBOX_UWP'"] -Db_pch=false -Dc_winlibs=[] -Dcpp_winlibs=[]

      # Step 5: Build Mesa for UWP
      - name: Build Mesa for UWP
        run: |
          meson compile -C build_release

      # Step 6: Install Mesa for UWP
      - name: Install Mesa for UWP
        run: |
          meson install -C build_release

      # Step 7: Upload built artifacts (Mesa DLLs and libraries)
      - name: Upload Artifacts (Mesa DLLs)
        uses: actions/upload-artifact@v4
        with:
          name: Mesa-UWP-Libraries
          path: build_release/*
          retention-days: 7
