name: Build Choreo

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Build Script
        run: cmd.exe /c build_choreo.bat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Choreo-Build
          path: |
            Choreo/output/** # Adjust based on actual output files
          retention-days: 7
