name: Build Simpsons:Hit & Run UWP

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW-w64 or LLVM
        run: |
          choco install mingw --force  # Install MinGW-w64 if not already installed
          echo "CC=mingw64-gcc" >> $GITHUB_ENV
          echo "CXX=mingw64-g++" >> $GITHUB_ENV
          echo "CFLAGS=-target x86_64-pc-windows-msvc -DWINAPI_FAMILY=WINAPI_FAMILY_APP" >> $GITHUB_ENV
          echo "CXXFLAGS=$CFLAGS" >> $GITHUB_ENV

      - name: Build Simpsons: Hit & Run UWP
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=C:/path/to/uwp-toolchain.cmake -DCMAKE_BUILD_TYPE=Release ..
          ninja

