name: Build Choreo Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-choreo:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Choreo CLI
      run: |
        # Download choreo-cli.exe from the repository
        curl -L -o choreo-cli.exe https://github.com/izzy2lost/Simpsons-Hit-Run/raw/main/choreo-cli.exe

    - name: Build Choreo Library
      run: |
        # Run the choreo-cli.exe to build the Choreo library
        .\choreo-cli.exe build --config "release"  # Adjust based on your actual build command

    - name: Verify Build Output
      run: |
        # Check if the build was successful, or look for output files
        if (Test-Path "./output") {
          Write-Host "Build completed successfully."
        } else {
          Write-Host "Build failed."
          exit 1
        }
