name: Build Choreo Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-choreo:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
        choco install curl

    - name: Download Choreo C++ Library
      run: |
        # Create directory for Choreo library and download ChoreoLib2025.json
        mkdir -p choreo
        cd choreo
        curl -L -o ChoreoLib2025.json https://lib.choreo.autos/dep/ChoreoLib2025.json

    - name: Install Choreo C++ Dependencies
      run: |
        # Use the C++ dependencies from the JSON file
        # Here, you might need to write a custom script or use a package manager to download ChoreoLib-cpp
        # For now, we'll just download the appropriate package manually as per the JSON configuration
        curl -L -o ChoreoLib-cpp-2025.0.3-windows-x86_64.zip https://lib.choreo.autos/dep/choreo/ChoreoLib-cpp/2025.0.3/windowsx86-64/ChoreoLib-cpp-2025.0.3-windows-x86_64.zip
        # Unzip the downloaded package
        tar -xvzf ChoreoLib-cpp-2025.0.3-windows-x86_64.zip

    - name: Build Choreo Library (C++)
      run: |
        # Assuming Choreo is built with CMake, create the build directory and run cmake
        mkdir -p choreo-build
        cd choreo-build
        cmake ../choreo
        cmake --build .

    - name: Verify Build Output
      run: |
        # Verify if Choreo library was successfully built
        if (Test-Path "choreo-build/Release/ChoreoLib.lib") {
          Write-Host "Choreo library built successfully."
        } else {
          Write-Host "Choreo build failed."
          exit 1
        }

    - name: Upload Choreo Library Artifact
      uses: actions/upload-artifact@v4
      with:
        name: choreo-library
        path: choreo-build/Release/ChoreoLib.lib
