name: Build Choreo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # You can change this to macOS or ubuntu-latest for cross-platform builds
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Ensure submodules are checked out if required

    - name: Set up Rust
      uses: actions/setup-rust@v1  # Ensure correct version is used
      with:
        rust-version: 1.70.0  # Set the Rust version you need

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the appropriate version of Node.js

    - name: Install pnpm
      run: |
        npm install -g pnpm  # Install pnpm globally

    - name: Install Node.js dependencies
      run: |
        pnpm install  # Install the necessary Node.js dependencies

    - name: Set up CMake
      uses: cmake/setup-cmake@v3  # Correct setup-cmake action
      with:
        cmake-version: '3.21'  # Specify the version needed for the build

    - name: Build Choreo (Windows)
      run: |
        # Make sure you have all the necessary tools installed (e.g., Visual Studio 2022)
        pnpm build  # Run the build command for Choreo (or adjust as needed)

    - name: Verify Build Output
      run: |
        # Check the build output or perform any post-build steps
        echo "Build completed successfully"
