name: Build Choreo Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-choreo:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
        choco install pnpm

    - name: Install Choreo Dependencies via pnpm
      run: |
        # Assuming you need to fetch the dependencies via pnpm from ChoreoLib2025.json
        mkdir -p choreo
        cd choreo
        curl -L -o ChoreoLib2025.json https://lib.choreo.autos/dep/ChoreoLib2025.json
        pnpm install

    - name: Build Choreo Library
      run: |
        cd choreo
        pnpm run build

    - name: Verify Build Output
      run: |
        # Check if the library was built
        if (Test-Path "choreo/build/Release/choreo.lib") {
          Write-Host "Choreo library built successfully."
        } else {
          Write-Host "Choreo build failed."
          exit 1
        }
