name: Build and Upload Artifacts

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # or the branch you want to trigger for PRs
jobs:
  build:
    steps:
      # Setup latest CMake
      - uses: lukka/get-cmake@latest

      # Setup vcpkg (ensures vcpkg is downloaded and built)
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          # Location for vcpkg sources (defaults to workspace)
          # If you need to specify a location, uncomment and set vcpkgDirectory.
          # vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      # Install the required dependencies using vcpkg
      - name: Install vcpkg dependencies
        run: |
          ./vcpkg install sdl2 openal-soft glad --triplet x64-uwp

      # Run CMake consuming CMakePreset.json and run vcpkg to build packages
      - name: Run CMake and build with vcpkg
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          testPreset: 'ninja-multi-vcpkg'
          # Optional: Additional args for CMake configuration and build
          configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
          buildPresetAdditionalArgs: "['--config Release']"
          
          uses: microsoft/setup-msbuild@v1
          with:
            vs-version: '2022'  # Ensure this matches the Visual Studio version you are using

      - name: Build with MSBuild
        run: |
          # Build the solution using MSBuild (adjust the configuration as needed)
          msbuild SRR2.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/bin/Release/*
            **/bin/Debug/*
            # Adjust paths to where your artifacts are being output
