name: Build and Upload Artifacts

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # or the branch you want to trigger for PRs

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup latest CMake
      - uses: lukka/get-cmake@latest

      # Run the PowerShell script to setup vcpkg and install dependencies
      - name: Setup vcpkg and Install Dependencies
        run: |
          powershell -ExecutionPolicy Bypass -File ./setup_vcpkg.ps1

      # Generate CMake project files with Visual Studio (MSVC toolchain)
      - name: Generate project files with CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX=./install

      # Build the project with Visual Studio
      - name: Build with Visual Studio
        run: |
          cmake --build build --config Release --target INSTALL
          
      # Optionally, run tests if needed
      - name: Run tests
        run: |
          ctest --test-dir build
