name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      # Run the PowerShell script to setup vcpkg and install dependencies
      - name: Setup vcpkg and Install Dependencies
        run: |
          powershell -ExecutionPolicy Bypass -File ./setup_vcpkg.ps1

      # Generate project files with Visual Studio (MSVC toolchain)
      - name: Generate project files with CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      # Build the Pure3D.vcxproj project with Visual Studio (without install)
      - name: Build Pure3D project with Visual Studio
        run: |
          msbuild "src/libs/pure3d/Pure3D.vcxproj" /p:Configuration=Release

      # Optionally, run tests if needed
      - name: Run tests
        run: |
          ctest --test-dir build
