name: Build and Upload Artifacts

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main  # or the branch you want to trigger for PRs

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Setup latest CMake
      - uses: lukka/get-cmake@latest

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the PowerShell script to setup vcpkg and install dependencies
      - name: Setup vcpkg and Install Dependencies
        run: |
          powershell -ExecutionPolicy Bypass -File ./setup_vcpkg.ps1

      # Run CMake consuming CMakePreset.json and run vcpkg to build packages
      - name: Run CMake and build with vcpkg
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-multi-vcpkg'
          testPreset: 'ninja-multi-vcpkg'
          # Optional: Additional args for CMake configuration and build
          configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"
          buildPresetAdditionalArgs: "['--config Release']"
          testPresetAdditionalArgs: "['--config Release']"
